export const WMO_CODE_DESCRIPTIONS: Record<number, Record<string, string>> = {
  0: { en: 'Clear sky', es: 'Cielo despejado', fr: 'Ciel dégagé', it: 'Cielo sereno', de: 'Klarer Himmel', uk: 'Ясне небо' },
  1: { en: 'Mainly clear', es: 'Principalmente despejado', fr: 'Généralement dégagé', it: 'Prevalentemente sereno', de: 'Hauptsächlich klar', uk: 'Переважно ясно' },
  2: { en: 'Partly cloudy', es: 'Parcialmente nublado', fr: 'Partiellement nuageux', it: 'Parzialmente nuvoloso', de: 'Teilweise bewölkt', uk: 'Частково хмарно' },
  3: { en: 'Overcast', es: 'Nublado', fr: 'Couvert', it: 'Coperto', de: 'Bedeckt', uk: 'Похмуро' },
  45: { en: 'Fog', es: 'Niebla', fr: 'Brouillard', it: 'Nebbia', de: 'Nebel', uk: 'Туман' },
  48: { en: 'Depositing rime fog', es: 'Niebla engelante', fr: 'Brouillard givrant', it: 'Nebbia sopraffusa', de: 'Reifnebel', uk: 'Паморозь' },
  51: { en: 'Light drizzle', es: 'Llovizna ligera', fr: 'Bruine légère', it: 'Pioviggine leggera', de: 'Leichter Nieselregen', uk: 'Легка мряка' },
  53: { en: 'Moderate drizzle', es: 'Llovizna moderada', fr: 'Bruine modérée', it: 'Pioviggine moderata', de: 'Mäßiger Nieselregen', uk: 'Помірна мряка' },
  55: { en: 'Dense drizzle', es: 'Llovizna densa', fr: 'Bruine forte', it: 'Pioviggine fitta', de: 'Dichter Nieselregen', uk: 'Сильна мряка' },
  56: { en: 'Light freezing drizzle', es: 'Llovizna helada ligera', fr: 'Bruine verglaçante légère', it: 'Pioviggine gelata leggera', de: 'Leichter gefrierender Nieselregen', uk: 'Легка замерзаюча мряка' },
  57: { en: 'Dense freezing drizzle', es: 'Llovizna helada densa', fr: 'Bruine verglaçante forte', it: 'Pioviggine gelata fitta', de: 'Dichter gefrierender Nieselregen', uk: 'Сильна замерзаюча мряка' },
  61: { en: 'Slight rain', es: 'Lluvia ligera', fr: 'Pluie faible', it: 'Pioggia debole', de: 'Leichter Regen', uk: 'Невеликий дощ' },
  63: { en: 'Moderate rain', es: 'Lluvia moderada', fr: 'Pluie modérée', it: 'Pioggia moderata', de: 'Mäßiger Regen', uk: 'Помірний дощ' },
  65: { en: 'Heavy rain', es: 'Lluvia intensa', fr: 'Forte pluie', it: 'Pioggia forte', de: 'Starker Regen', uk: 'Сильний дощ' },
  66: { en: 'Light freezing rain', es: 'Lluvia helada ligera', fr: 'Pluie verglaçante légère', it: 'Pioggia gelata leggera', de: 'Leichter gefrierender Regen', uk: 'Легкий замерзаючий дощ' },
  67: { en: 'Heavy freezing rain', es: 'Lluvia helada intensa', fr: 'Forte pluie verglaçante', it: 'Pioggia gelata forte', de: 'Starker gefrierender Regen', uk: 'Сильний замерзаючий дощ' },
  71: { en: 'Slight snow fall', es: 'Nevada ligera', fr: 'Faible chute de neige', it: 'Leggera nevicata', de: 'Leichter Schneefall', uk: 'Невеликий сніг' },
  73: { en: 'Moderate snow fall', es: 'Nevada moderada', fr: 'Chute de neige modérée', it: 'Nevicata moderata', de: 'Mäßiger Schneefall', uk: 'Помірний сніг' },
  75: { en: 'Heavy snow fall', es: 'Nevada intensa', fr: 'Forte chute de neige', it: 'Forte nevicata', de: 'Starker Schneefall', uk: 'Сильний сніг' },
  77: { en: 'Snow grains', es: 'Granos de nieve', fr: 'Grains de neige', it: 'Grani di neve', de: 'Schneekörner', uk: 'Снігові зерна' },
  80: { en: 'Slight rain showers', es: 'Chubascos ligeros', fr: 'Averses de pluie faibles', it: 'Rovesci deboli', de: 'Leichte Regenschauer', uk: 'Невеликі зливи' },
  81: { en: 'Moderate rain showers', es: 'Chubascos moderados', fr: 'Averses de pluie modérées', it: 'Rovesci moderati', de: 'Mäßige Regenschauer', uk: 'Помірні зливи' },
  82: { en: 'Violent rain showers', es: 'Chubascos violentos', fr: 'Averses de pluie violentes', it: 'Rovesci violenti', de: 'Heftige Regenschauer', uk: 'Сильні зливи' },
  85: { en: 'Slight snow showers', es: 'Chubascos de nieve ligeros', fr: 'Averses de neige faibles', it: 'Deboli rovesci di neve', de: 'Leichte Schneeschauer', uk: 'Невеликі снігопади' },
  86: { en: 'Heavy snow showers', es: 'Chubascos de nieve intensos', fr: 'Averses de neige fortes', it: 'Forti rovesci di neve', de: 'Starke Schneeschauer', uk: 'Сильні снігопади' },
  95: { en: 'Thunderstorm', es: 'Tormenta', fr: 'Orage', it: 'Temporale', de: 'Gewitter', uk: 'Гроза' },
  96: { en: 'Thunderstorm with slight hail', es: 'Tormenta con granizo ligero', fr: 'Orage avec grêle légère', it: 'Temporale con grandine leggera', de: 'Gewitter mit leichtem Hagel', uk: 'Гроза з невеликим градом' },
  99: { en: 'Thunderstorm with heavy hail', es: 'Tormenta con granizo intenso', fr: 'Orage avec grêle forte', it: 'Temporale con grandine forte', de: 'Gewitter mit schwerem Hagel', uk: 'Гроза з сильним градом' }
};
